force-app/main/default/objects/EBS_Order__c/EBS_Order__c.object-meta.xml
<CustomObject>
    <label>EBS Order</label>
    <nameField>
        <displayFormat>EBSO{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EBS Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EBS_Order__c/fields/Acc_PO_Contact__c.field-meta.xml
<CustomField>
    <fullName>Acc_PO_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Acc PO Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>EBS Orders (Acc PO Contact)</relationshipLabel>
    <relationshipName>EBS_Orders3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EBS Orders</relationshipLabel>
    <relationshipName>EBS_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/Customer_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account_Number__c</fullName>
    <label>Customer Account Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/EBS_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>EBS_Order_Number__c</fullName>
    <externalId>true</externalId>
    <label>EBS Order Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/PO_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>PO_Contact_Email__c</fullName>
    <label>PO Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/Template_Name_Formula__c.field-meta.xml
<CustomField>
    <fullName>Template_Name_Formula__c</fullName>
    <formula
  >IF(OR(Account_Name__r.Customer_Category__c = &apos;NON-VERIFIED&apos;,Account_Name__r.Logo__c = &apos;CALENDAR COOP&apos;) ,
&apos;Calendar Coop PO Receipt v1&apos;,
IF(OR(Account_Name__r.Customer_Category__c = &apos;CHURCH&apos;,Account_Name__r.Customer_Category__c = &apos;BOOKSTORE&apos;),
&apos;Anchor Wallace PO Receipt Notification v1&apos;,
IF(AND(OR(Account_Name__r.Customer_Category__c = &apos;NON-VERIFIED&apos;,Account_Name__r.Logo__c = &apos;CALENDAR COOP&apos;),
PO_Total_Difference__c  &lt; 50), &apos;Calendar Coop OE No Touch less then 50 v1&apos;,
IF(AND(OR(Account_Name__r.Customer_Category__c = &apos;CHURCH&apos;,Account_Name__r.Customer_Category__c = &apos;BOOKSTORE&apos;),
PO_Total_Difference__c  &lt; 50), &apos;Anchor Wallace OE No Touch less 50 Notification v1&apos;, 
IF(AND(OR(Account_Name__r.Customer_Category__c != &apos;NON-VERIFIED&apos;,
										Account_Name__r.Logo__c != &apos;CALENDAR COOP&apos;,Account_Name__r.Customer_Category__c != &apos;CHURCH&apos;,
										Account_Name__r.Customer_Category__c != &apos;BOOKSTORE&apos;),PO_Total_Difference__c  &lt; 50), 
&apos;Koozie Group OE No Touch less 50 Notification v1&apos;,&apos;Koozie Group PO Receipt Email v1&apos;)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Template Name Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NotificationtriggerHandlerTest.cls
/**
 * @description       : 
 * @author            : Mohammad Arafat Ali
 * @group             : 
 * @last modified on  : 12-20-2022
 * @last modified by  : Mohammad Arafat Ali
**/
@istest
public without sharing class NotificationtriggerHandlerTest {

    private class RestMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            String fullJson = 'Response';

            HTTPResponse res = new HTTPResponse();
            res.setHeader('Content-Type', 'text/json');
            res.setBody(fullJson);
            res.setStatusCode(200);
            return res;
        }
    }
    public static testMethod void replaceFields() {
        List<EBS_Order__c> ebsList = new List<EBS_Order__c>();

        Id accRecTypId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customers').getRecordTypeId();
        Id conRecTypId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('CRM Contact').getRecordTypeId();

        Account acc= new Account();
        acc.Name = 'Test Account';
        acc.Acc_PO_Contact_Email__c = 'arafata@damco.com';
        acc.Customer_Account_Number__c = '123456';
        acc.Customer_PO_Number__c = '12345';
        acc.Customer_Category__c  = 'CHURCH'; 
        acc.RecordTypeId = accRecTypId;
        insert acc;

        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'Contact';
        con.AccountId = acc.Id;
        con.Email = 'Test@testing.com';
        con.RecordTypeId = conRecTypId;
        con.Acc_PO_Contact__c = True;
        insert con;

        EBS_Order__c ebsOrder = new EBS_Order__c();
        ebsOrder.Account_Name__c = acc.Id; 
        ebsOrder.PO_Contact_Email__c = 'arafata@damco.com'; 
        ebsOrder.Customer_Account_Number__c = '123456'; 
        ebsOrder.EBS_Order_Number__c = '1234'; 
        Insert ebsOrder;
        
        Notification__c notif = new Notification__c(); 
        notif.EBS_Order__c = ebsOrder.Id;  
        //notif.Template_Name_Formula__c = ebsOrder.Template_Name_Formula__c;
        Insert notif;

        Test.setMock(HttpCalloutMock.class, new RestMock());
        Test.startTest();
        System.debug('==== ebsOrder.Template_Name_Formula__c ===='+ebsOrder.Template_Name_Formula__c);
        NotificationTriggerHandler.replaceField(new List<EBS_Order__c>{ebsOrder});
        Test.stopTest();
        NotificationTriggerHandler.codeCoverage();
    }  
}