force-app/main/default/objects/EBS_Order__c/EBS_Order__c.object-meta.xml
<CustomObject>
    <label>EBS Order</label>
    <nameField>
        <displayFormat>EBSO{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EBS Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EBS_Order__c/fields/Acc_Order_Confirm_Contact_To_Email__c.field-meta.xml
<CustomField>
    <fullName>Acc_Order_Confirm_Contact_To_Email__c</fullName>
    <label>Acc Order Confirm Contact To Email</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/Acc_PO_Contact_To_Email__c.field-meta.xml
<CustomField>
    <fullName>Acc_PO_Contact_To_Email__c</fullName>
    <label>Acc PO Contact To Email</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/Acc_Shipping_Notif_Contact_To_Email__c.field-meta.xml
<CustomField>
    <fullName>Acc_Shipping_Notif_Contact_To_Email__c</fullName>
    <label>Acc Shipping Notif Contact To Email</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/Additional_Emails__c.field-meta.xml
<CustomField>
    <fullName>Additional_Emails__c</fullName>
    <label>Additional Emails</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/Customer_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account_Number__c</fullName>
    <label>Customer Account Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/EBS_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>EBS_Order_Number__c</fullName>
    <externalId>true</externalId>
    <label>EBS Order Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/FindingOrderFromCustAccAndOrderNum.cls
/**
 * @description       : 
 * @author            : Kumar Saurav
 * @group             : 
 * @last modified on  : 08-01-2023
 * @last modified by  : Kumar Saurav
 * JIRA TICKET        : SF-478
**/
@RestResource(urlMapping='/FindEBSOrder/*')
global without sharing class FindingOrderFromCustAccAndOrderNum {
    @HttpPOST
    global static void findOrder(String custAccNum, String ordernum ){
        RestResponse response = RestContext.response;
        response.addHeader('Content-Type', 'application/json');
        String jsonS = '';
        if(String.isNotBlank(custAccNum) && String.isNotBlank(ordernum)){
            for(EBS_Order__c order : [
                SELECT Id, Customer_Account_Number__c, EBS_Order_Number__c,  Acc_PO_Contact_To_Email__c, Acc_Order_Confirm_Contact_To_Email__c, Acc_Shipping_Notif_Contact_To_Email__c,Additional_Emails__c
                FROM EBS_Order__c
                WHERE  
                Customer_Account_Number__c =: custAccNum AND 
                EBS_Order_Number__c =: ordernum LIMIT 1
                
            ]){
                 jsonS = OrderJSONGenerator.orderJSON(order).getAsString();
                response.statusCode = 200;
                response.responseBody =  Blob.valueOf(jsonS);
                //jsonS = gen.getAsString();
                System.debug('====jsonS===='+jsonS);
            }
        }else{
            jsonS = 'Missing required parameters';
            response.statusCode = 400;
            response.responseBody =  Blob.valueOf(jsonS);
        }
    }
}