force-app/main/default/objects/EBS_Order__c/EBS_Order__c.object-meta.xml
<CustomObject>
    <label>EBS Order</label>
    <nameField>
        <displayFormat>EBSO{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EBS Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EBS_Order__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <inlineHelpText>The EBS order creation date</inlineHelpText>
    <label>Effective Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/testSFDCOrderCPurge.cls
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Test class for order purge batch class and schedulable interface
@isTest
private class testSFDCOrderCPurge {

    static testMethod void SFDCOrderPurgeTest() {        

        Date todDate = system.today();
        Date purgeDate = todDate.addMonths(-29);     
        
        test.starttest();
         
        EBS_Order__c eOrder = new EBS_Order__c(Effective_Date__c=purgeDate);
        insert eOrder;
         
        sfdcOrderPurgeSchedule myClass = new sfdcOrderPurgeSchedule ();   
        String chron = '0 0 23 * * ?';        
        system.schedule('Test Sched', chron, myClass);
        test.stopTest();
    }
}
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////