force-app/main/default/objects/EBS_Order__c/EBS_Order__c.object-meta.xml
<CustomObject>
    <label>EBS Order</label>
    <nameField>
        <displayFormat>EBSO{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EBS Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EBS_Order__c/fields/Acc_PO_Contact__c.field-meta.xml
<CustomField>
    <fullName>Acc_PO_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Acc PO Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>EBS Orders (Acc PO Contact)</relationshipLabel>
    <relationshipName>EBS_Orders3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EBS Orders</relationshipLabel>
    <relationshipName>EBS_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/Customer_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account_Number__c</fullName>
    <label>Customer Account Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/Customer_PO__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO__c</fullName>
    <label>Customer PO</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/EBS_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>EBS_Order_Number__c</fullName>
    <externalId>true</externalId>
    <label>EBS Order Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>EBS Orders</relationshipLabel>
    <relationshipName>EBS_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/PO_Contact__c.field-meta.xml
<CustomField>
    <fullName>PO_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PO Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>EBS Orders</relationshipLabel>
    <relationshipName>EBS_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/PO_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>PO_Contact_Email__c</fullName>
    <label>PO Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>Quote_Number__c</fullName>
    <label>Quote Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/Quote_Request__c.field-meta.xml
<CustomField>
    <fullName>Quote_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Request</label>
    <referenceTo>Quote_Request__c</referenceTo>
    <relationshipLabel>EBS Orders</relationshipLabel>
    <relationshipName>EBS_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/Quote_Request__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Quote_Request_Compact_Layout</compactLayoutAssignment>
    <label>Quote Request</label>
    <nameField>
        <displayFormat>QR-{0000}</displayFormat>
        <label>Quote Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.AccountNumber</field>
            <operation>equals</operation>
            <valueField>Account.AccountNumber</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Requests</relationshipLabel>
    <relationshipName>Quote_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quote Requests</relationshipLabel>
    <relationshipName>Quote_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quote Requests</relationshipLabel>
    <relationshipName>Quote_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>Quote_Number__c</fullName>
    <displayFormat>Q-{0000}-{MMDDYY}</displayFormat>
    <label>Quote Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/populateQuoteReqAndOpp_Test.cls
@isTest
private class populateQuoteReqAndOpp_Test {
    
    @isTest
    public static void testMethodForOppAndQuoteCreation(){
        Test.setMock(HttpCalloutMock.class, new MockHTTPResponseGenerator());
        Id accRecTypId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customers').getRecordTypeId();
        Id conRecTypId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('CRM Contact').getRecordTypeId();
        Map<String,EBS_Order__c> quoteNumOrderMap = new Map<String,EBS_Order__c>();
        
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.RecordTypeId = accRecTypId;
        acc.Customer_Account_Number__c = '12345678';
        acc.Customer_PO_Number__c = '123456';
        insert acc;
        
        Contact cont = new Contact();
        cont.firstname = 'First';
        cont.lastname = 'Test Name';  
        cont.AccountId = acc.Id;
        cont.Email = 'firsttestname@testing.com';
        cont.Phone = '407-508-1313';
        cont.RecordTypeId = conRecTypId;
        cont.Acc_PO_Contact__c = True;
        insert cont;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'test';
        opp.StageName = 'Proposal';
        opp.CloseDate = System.today();
        //opp.Quote_Number__c = 'OQR-034477';
        opp.Contact__c = cont.Id;
        insert opp;    
        
        Opportunity oppquotenumber = [SELECT Quote_Number__c FROM Opportunity WHERE Quote_Number__c LIKE '%QR%' LIMIT 1];
        //Without Case
        EBS_Order__c eo = new EBS_Order__c();
        eo.Account_Name__c = acc.Id;
        eo.PO_Contact__c = cont.Id;
        eo.PO_Contact_Email__c = 'contact1@ebsorder.com'; 
        eo.Customer_Account_Number__c = '1234567'; 
        eo.Order_Type__c = 'Standard';
        eo.Customer_PO__c = 'PK11001436L1';
        eo.Quote_Number__c = 'QR-144031';
        eo.Quote_Number__c = oppquotenumber.Quote_Number__c;
        eo.EBS_Order_Number__c = '27903373661';
        insert eo;
        
        eo.Opportunity__c = opp.Id;
        update eo;
        Quote_Request__c qr = new Quote_Request__c();
        qr.Contact__c = cont.Id;
        qr.Account__c = acc.Id;
        qr.Opportunity__c = opp.Id;
        insert qr;
        List<EBS_Order__c> eoList = new List<EBS_Order__c>(); 
        eoList.add(eo);
        quoteNumOrderMap.put('QR-14403',eo);
        
        Map<String, List<EBS_Order__c>> orderMap = new Map<String, List<EBS_Order__c>>();
        orderMap.put('QR-14403', new List<EBS_Order__c>{eo});
        
        // Test.startTest();
        populateQuoteReqAndOpp.updateOrderWithQuoteAndOpp(orderMap);
    }
    
    @isTest
    public static void testupdateEBSOrderFromQuote() {
        Id accRecTypId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customers').getRecordTypeId();
        Id conRecTypId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('CRM Contact').getRecordTypeId();
        Map<String,EBS_Order__c> quoteNumOrderMap = new Map<String,EBS_Order__c>();
        Account acc2 = new Account();
        acc2.Name = 'Test Account2';
        acc2.RecordTypeId = accRecTypId;
        acc2.Customer_Account_Number__c = '123456789';
        acc2.Customer_PO_Number__c = '1234567';
        insert acc2;
        
        Contact cont = new Contact();
        cont.firstname = 'First';
        cont.lastname = 'Test Name';  
        cont.AccountId = acc2.Id;
        cont.Email = 'firsttestname@testing.com';
        cont.Phone = '407-508-1313';
        cont.RecordTypeId = conRecTypId;
        cont.Acc_PO_Contact__c = True;
        insert cont;
        Opportunity opp = new Opportunity();
        opp.Name = 'test';
        opp.StageName = 'Proposal';
        opp.CloseDate = System.today(); 
        opp.Contact__c = cont.Id;
        insert opp;        
        //Without Case
        Quote_Request__c qr = new Quote_Request__c();
        qr.Contact__c = cont.Id;
        qr.Account__c = acc2.Id;
        qr.Opportunity__c = opp.Id;
        insert qr;
        Quote_Request__c quotenumber = [SELECT Quote_Number__c FROM Quote_Request__c WHERE Quote_Number__c LIKE '%Q%' LIMIT 1];
        system.debug('quotenumber---> '+quotenumber);
        EBS_Order__c eo = new EBS_Order__c();
        eo.Account_Name__c = acc2.Id;
        eo.PO_Contact__c = cont.Id;
        eo.PO_Contact_Email__c = 'contact@ebsorder.com'; 
        eo.Customer_Account_Number__c = '123456'; 
        eo.Order_Type__c = 'Standard';
        eo.Customer_PO__c = 'PK11001436L';
        eo.Quote_Number__c = quotenumber.Quote_Number__c;
        eo.EBS_Order_Number__c = '2790337366';
        insert eo;
        
        Test.startTest();
        List<EBS_Order__c> eoList = new List<EBS_Order__c>(); 
        eoList.add(eo);
        quoteNumOrderMap.put(quotenumber.Quote_Number__c,eo);
                
        
        Map<String, List<EBS_Order__c>> orderMap = new Map<String, List<EBS_Order__c>>();
        orderMap.put(quotenumber.Quote_Number__c, new List<EBS_Order__c>{eo});
        
        populateQuoteReqAndOpp.updateOrderWithQuoteAndOpp(orderMap);
        Test.setMock(HttpCalloutMock.class, new MockHTTPResponseGenerator());
        Test.stopTest();
        
    }
    
    @isTest
    public static void testupdateEBSOrderFromQuote2() {
        Id accRecTypId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customers').getRecordTypeId();
        Id conRecTypId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('CRM Contact').getRecordTypeId();
        Map<String,EBS_Order__c> quoteNumOrderMap = new Map<String,EBS_Order__c>();
        Account acc2 = new Account();
        acc2.Name = 'Test Account2';
        acc2.RecordTypeId = accRecTypId;
        acc2.Customer_Account_Number__c = '123456789';
        acc2.Customer_PO_Number__c = '1234567';
        insert acc2;
        
        Contact cont = new Contact();
        cont.firstname = 'First';
        cont.lastname = 'Test Name';  
        cont.AccountId = acc2.Id;
        cont.Email = 'firsttestname@testing.com';
        cont.Phone = '407-508-1313';
        cont.RecordTypeId = conRecTypId;
        cont.Acc_PO_Contact__c = True;
        insert cont;
        Opportunity opp = new Opportunity();
        opp.Name = 'test';
        opp.StageName = 'Proposal';
        opp.CloseDate = System.today(); 
        opp.Contact__c = cont.Id;
        insert opp;        
        //Without Case
        Quote_Request__c qr = new Quote_Request__c();
        qr.Contact__c = cont.Id;
        qr.Account__c = acc2.Id;
        qr.Opportunity__c = opp.Id;
        insert qr;
        Quote_Request__c quotenumber = [SELECT Quote_Number__c, Name  FROM Quote_Request__c WHERE Quote_Number__c LIKE '%Q%' LIMIT 1];
        EBS_Order__c eo = new EBS_Order__c();
        eo.Account_Name__c = acc2.Id;
        eo.PO_Contact__c = cont.Id;
        eo.PO_Contact_Email__c = 'contact@ebsorder.com'; 
        eo.Customer_Account_Number__c = '123456'; 
        eo.Order_Type__c = 'Standard';
        eo.Customer_PO__c = 'PK11001436L';
        eo.Quote_Number__c = quotenumber.Name;
        eo.EBS_Order_Number__c = '2790337366';
        insert eo;
        
        Test.startTest();
        List<EBS_Order__c> eoList = new List<EBS_Order__c>(); 
        eoList.add(eo);
        quoteNumOrderMap.put(quotenumber.Name,eo);
        
        
        Map<String, List<EBS_Order__c>> orderMap = new Map<String, List<EBS_Order__c>>();
        orderMap.put('OQR-12345', new List<EBS_Order__c>{eo});
        
        populateQuoteReqAndOpp.updateOrderWithQuoteAndOpp(orderMap);
        Test.setMock(HttpCalloutMock.class, new MockHTTPResponseGenerator());
        Test.stopTest();
        
    }
}