force-app/main/default/objects/EBS_Order__c/EBS_Order__c.object-meta.xml
<CustomObject>
    <label>EBS Order</label>
    <nameField>
        <displayFormat>EBSO{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EBS Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EBS_Order__c/fields/PO_Contact__c.field-meta.xml
<CustomField>
    <fullName>PO_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PO Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>EBS Orders</relationshipLabel>
    <relationshipName>EBS_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderMessaging.cls
/**
 * @description       : 
 * @author            : ritesh.kumar@kooziegroup.com
 * @group             : 
 * @last modified on  : 09-04-2024
 * @last modified by  : ritesh.kumar@kooziegroup.com
**/
public with sharing class OrderMessaging {

    @AuraEnabled
    public static String getMessagingSessionId(String recordId){
        String messagingSessionId = '';
        String endUserId = '';
        if(String.isNotBlank(recordId)){ 
             

            for(EBS_Order__c order : [
                    SELECT Id, PO_Contact__c 
                    FROM EBS_Order__c 
                    WHERE Id =: recordId AND 
                    PO_Contact__c != NULL 
            ]){
                endUserId = order.PO_Contact__c;
            } 

        }
        System.debug(LoggingLevel.INFO, '===== endUserId: '+endUserId);
        if(String.isNotBlank(endUserId)){ 
            for(MessagingSession messageData : [
                SELECT Id, EndUserContactId 
                FROM MessagingSession 
                WHERE EndUserContactId =: endUserId ORDER BY CreatedDate DESC LIMIT 1
            ]) { 
                messagingSessionId = messageData.Id;
            } 
            
        }
        System.debug(LoggingLevel.INFO, '===== messagingSessionId: '+messagingSessionId);
        Return messagingSessionId;

    }

 

    @AuraEnabled
    public static MessagingSession getRecentMessagingSession(String recordId){
        MessagingSession msg = new MessagingSession();
        String endUserId = '';
        if(String.isNotBlank(recordId)){ 
             

            for(EBS_Order__c order : [
                    SELECT Id, PO_Contact__c 
                    FROM EBS_Order__c 
                    WHERE Id =: recordId AND 
                    PO_Contact__c != NULL 
            ]){
                endUserId = order.PO_Contact__c;
            } 

        }

         for(MessagingSession messageData : [
            SELECT ChannelEndUserFormula, ChannelKey, ConversationId, MessagingEndUserId, SessionKey, Status, PreviewDetails
            FROM MessagingSession 
            WHERE EndUserContactId =: endUserId ORDER BY CreatedDate DESC LIMIT 1
        ]){ 
            msg = messageData;
        }

        return msg;

    }
}