force-app/main/default/objects/EBS_Order__c/EBS_Order__c.object-meta.xml
<CustomObject>
    <label>EBS Order</label>
    <nameField>
        <displayFormat>EBSO{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EBS Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EBS_Order__c/fields/Acc_Order_Confirm_Contact_To_Email__c.field-meta.xml
<CustomField>
    <fullName>Acc_Order_Confirm_Contact_To_Email__c</fullName>
    <label>Acc Order Confirm Contact To Email</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/Acc_PO_Contact_To_Email__c.field-meta.xml
<CustomField>
    <fullName>Acc_PO_Contact_To_Email__c</fullName>
    <label>Acc PO Contact To Email</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/Acc_Shipping_Notif_Contact_To_Email__c.field-meta.xml
<CustomField>
    <fullName>Acc_Shipping_Notif_Contact_To_Email__c</fullName>
    <label>Acc Shipping Notif Contact To Email</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/Additional_Emails__c.field-meta.xml
<CustomField>
    <fullName>Additional_Emails__c</fullName>
    <label>Additional Emails</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/OrderJSONGenerator.cls
/**
 * @description       : 
 * @author            : Kumar Saurav
 * @group             : 
 * @last modified on  : 08-01-2023
 * @last modified by  : Kumar Saurav
 * JIRA TICKET        : SF-478
**/
global without sharing class OrderJSONGenerator {
    global static JSONGenerator orderJSON(EBS_Order__c order ){
         JSONGenerator gen = JSON.createGenerator (true);
            gen.writeStartObject();
             if(order.Id != null){
                gen.writeStringField('SFId', order.Id);
            }else{
                gen.writeNullField('SFId');
            }
            if(String.isNotBlank( order.Acc_PO_Contact_To_Email__c)){
                gen.writeStringField('accPOContactToEmail', order.Acc_PO_Contact_To_Email__c);
            }else{
                gen.writeNullField('accPOContactToEmail');
            }
            if(String.isNotBlank( order.Acc_Order_Confirm_Contact_To_Email__c)){
                gen.writeStringField('accOrderConfirmContactToEmail', order.Acc_Order_Confirm_Contact_To_Email__c);
            }else{
                gen.writeNullField('accOrderConfirmContactToEmail');
            }
            if(String.isNotBlank( order.Acc_Shipping_Notif_Contact_To_Email__c)){
                gen.writeStringField('accShippingNotifContactToEmail', order.Acc_Shipping_Notif_Contact_To_Email__c);
            }else{
                gen.writeNullField('accShippingNotifContactToEmail');
            }
            if(String.isNotBlank( order.Additional_Emails__c)){
                gen.writeStringField('additionalEmail', order.Additional_Emails__c);
            }else{
                gen.writeNullField('additionalEmail');
            }
            gen.writeEndObject(); 
        return gen;
    }

}