force-app/main/default/objects/EBS_Order__c/EBS_Order__c.object-meta.xml
<CustomObject>
    <label>EBS Order</label>
    <nameField>
        <displayFormat>EBSO{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EBS Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EBS_Order__c/fields/Acc_PO_Contact__c.field-meta.xml
<CustomField>
    <fullName>Acc_PO_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Acc PO Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>EBS Orders (Acc PO Contact)</relationshipLabel>
    <relationshipName>EBS_Orders3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EBS Orders</relationshipLabel>
    <relationshipName>EBS_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/Customer_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account_Number__c</fullName>
    <label>Customer Account Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/EBS_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>EBS_Order_Number__c</fullName>
    <externalId>true</externalId>
    <label>EBS Order Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/Order_Confirm_Contact__c.field-meta.xml
<CustomField>
    <fullName>Order_Confirm_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Confirm Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>EBS Orders (Order Confirm Contact)</relationshipLabel>
    <relationshipName>EBS_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/PO_Contact__c.field-meta.xml
<CustomField>
    <fullName>PO_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PO Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>EBS Orders</relationshipLabel>
    <relationshipName>EBS_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/PO_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>PO_Contact_Email__c</fullName>
    <label>PO Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/EBS_Order__c/fields/Shipping_Notif_Contact__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Notif_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Notif Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>EBS Orders (Shipping Notif Contact)</relationshipLabel>
    <relationshipName>EBS_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PopulateCommunicationEmailTest.cls
@Istest
public class PopulateCommunicationEmailTest {
    
    private class RestMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HTTPResponse res = new HTTPResponse();
            res.setHeader('Content-Type', 'text/json'); 
            res.setBody('{"EventResponse":{"EventBusinessID":"123450","EventStatus":"SUCCESS","EventStatusMessage":"Successfully Completed","AccountData":{"SFId":"003XXXXXXXXXXXXXXX","WebId":"","AccountNo":"1234543DD"}}}');
            res.setStatusCode(200);
            return res;
        }
    }
    
    @TestSetup
    public static void setupData(){
        TestDataFactory.loadAppSetting();
        Test.setMock(HttpCalloutMock.class, new RestMock());
        Account accountInfo  = TestDataFactory.createAccount('Test Account','0123645','Customers',TRUE);
        Contact contactInfo = TestDataFactory.createContact('Test', 'Test', accountInfo.Id, 'CRM Contact', FALSE);
        contactInfo.Acc_Shipping_Contact__c = TRUE;
        contactInfo.Acc_Order_Acknowledgement__c = TRUE;
        contactInfo.Acc_PO_Contact__c = TRUE;
        Insert contactInfo;
    }
    
    @Istest
    public static void TagNewContactTest() {
        Id accountId = [SELECT Id FROM Account WHERE Customer_Account_Number__c = '0123645' LIMIT 1 ].Id;
        Test.setMock(HttpCalloutMock.class, new RestMock());        
        EBS_Order__c ebsOrder = new EBS_Order__c();
        ebsOrder.PO_Contact_Email__c = 'test23@test.com'; 
        ebsOrder.Customer_Account_Number__c = '0123645'; 
        ebsOrder.EBS_Order_Number__c = '123';
        ebsOrder.Account_Name__c = accountId;
        Test.startTest();
        Insert ebsOrder;
        EBS_Order__c [] orders = [
            SELECT 
            Id, Shipping_Notif_Contact__c, Order_Confirm_Contact__c,PO_Contact__c 
            FROM 
            EBS_Order__c  
            WHERE 
            Shipping_Notif_Contact__c != null AND 
            Order_Confirm_Contact__c != null AND 
            PO_Contact__c != null
        ];
        
        Contact [] Contacts = [SELECT Id,Email FROM Contact]; 
        System.assertEquals(true, orders.size() > 0);
        System.assertEquals(true, Contacts.size()>1);
        Test.stopTest();
    }
    
    @Istest
    public static void TagOldContactTest() {
        
        Id accountId = [SELECT Id FROM Account WHERE Customer_Account_Number__c = '0123645' LIMIT 1 ].Id;
        Test.setMock(HttpCalloutMock.class, new RestMock());        
        EBS_Order__c ebsOrder = new EBS_Order__c();
        ebsOrder.PO_Contact_Email__c = 'test@test.com'; 
        ebsOrder.Customer_Account_Number__c = '0123645'; 
        ebsOrder.EBS_Order_Number__c = '123';
        ebsOrder.Account_Name__c = accountId;
        Test.startTest();
        Insert ebsOrder;
        
        // Query Order
        EBS_Order__c [] orders = [
            SELECT 
            Id, Shipping_Notif_Contact__c, Order_Confirm_Contact__c,PO_Contact__c 
            FROM 
            EBS_Order__c  
            WHERE 
            Shipping_Notif_Contact__c != null AND 
            Order_Confirm_Contact__c != null AND 
            PO_Contact__c != null
        ];
        
        //Query Contact        
        Contact [] Contacts = [SELECT Id FROM Contact]; 
        System.assertEquals(true, orders.size() > 0);
        System.assertEquals(true, Contacts.size() > 0);
        Test.stopTest();
    }
    
}