force-app/main/default/objects/Quote_Request__c/Quote_Request__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Quote_Request_Compact_Layout</compactLayoutAssignment>
    <label>Quote Request</label>
    <nameField>
        <displayFormat>QR-{0000}</displayFormat>
        <label>Quote Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.AccountNumber</field>
            <operation>equals</operation>
            <valueField>Account.AccountNumber</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Requests</relationshipLabel>
    <relationshipName>Quote_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request in Draft</fullName>
                <default>true</default>
                <label>Request in Draft</label>
            </value>
            <value>
                <fullName>Request Submitted</fullName>
            </value>
            <value>
                <fullName>Request Received</fullName>
            </value>
            <value>
                <fullName>Request in Progress</fullName>
            </value>
            <value>
                <fullName>Request Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/attachPDFToQuoteRequest_Test.cls
/**
 * @description       : 
 * @author            : Sandeep Reddy
 * @group             : 
 * @last modified on  : 12-19-2022
 * @last modified by  : Sandeep Reddy
**/
@isTest
public class attachPDFToQuoteRequest_Test {
  @TestSetup
  static void makeData(){
    Account acc = TestData.createAccount(false);
    acc.Name = 'test';
    acc.Customer_Account_Number__c = '12345';
    acc.Routing_Override__c = 'Calendar Dedicated';
    acc.Logo__c ='Calendar Coop';
    insert acc;
    Quote_Request__c QuoteReq = new Quote_Request__c();
    QuoteReq.Account__c = acc.id;
    QuoteReq.Stage__c = 'Request in Draft';
    insert QuoteReq;
  }
  @isTest
  public static void TestQuoteCalenderPDf(){
    Quote_Request__c QuoteReq = [SELECT Id FROM Quote_Request__c LIMIT 1];
    test.startTest();
      PageReference pageRef = Page.Calendar_Quote_PDF;
      Test.setCurrentPage(pageRef);
      ApexPages.currentPage().getParameters().put('Recordid', QuoteReq.id);
      attachPDFToQuoteRequest obj = new attachPDFToQuoteRequest();
      attachPDFToQuoteRequest.attachPDF(QuoteReq.id,'Calendar');
    test.stopTest();
  }
  @isTest
  public static void TestQuoteNonCalenderPDf(){
    Quote_Request__c QuoteReq = [SELECT Id FROM Quote_Request__c LIMIT 1];
    ContentVersion testContentVersion = new ContentVersion();
    testContentVersion.Title = 'Test Content';
    testContentVersion.VersionData = Blob.valueOf('Test Content Version Data');
    testContentVersion.PathOnClient = 'testfile.txt';
    insert testContentVersion;
    ContentDocumentLink testContentDocumentLink = new ContentDocumentLink();
    testContentDocumentLink.ContentDocumentId = [SELECT Id FROM ContentDocument WHERE Id IN (SELECT ContentDocumentId FROM ContentVersion WHERE Id = :testContentVersion.Id)].Id;
    testContentDocumentLink.LinkedEntityId = QuoteReq.Id;
    testContentDocumentLink.ShareType = 'V';
    insert testContentDocumentLink;
    test.startTest();
      PageReference pageRef = Page.HS_Quote_PDF;
      Test.setCurrentPage(pageRef);
      ApexPages.currentPage().getParameters().put('Recordid', QuoteReq.id);
      attachPDFToQuoteRequest obj = new attachPDFToQuoteRequest();
      attachPDFToQuoteRequest.attachPDF(QuoteReq.id,'HS_Quote');
    test.stopTest();
  }
  @isTest
  private static void testScenario(){
    Quote_Request__c testQuoteRequest = new Quote_Request__c();
    insert testQuoteRequest;
    ApexPages.StandardController controller = new ApexPages.StandardController(testQuoteRequest);
    test.startTest();
      attachPDFToQuoteRequest controllerExtension = new attachPDFToQuoteRequest(controller);
    test.stoptest();
  }
}