force-app/main/default/objects/Quote_Request__c/Quote_Request__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Quote_Request_Compact_Layout</compactLayoutAssignment>
    <label>Quote Request</label>
    <nameField>
        <displayFormat>QR-{0000}</displayFormat>
        <label>Quote Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.AccountNumber</field>
            <operation>equals</operation>
            <valueField>Account.AccountNumber</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Requests</relationshipLabel>
    <relationshipName>Quote_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Additional_Quantities_2__c.field-meta.xml
<CustomField>
    <fullName>Additional_Quantities_2__c</fullName>
    <description>If any Additional Quantities are mentioned</description>
    <inlineHelpText
  >If any Additional Quantities are mentioned - Please specify here</inlineHelpText>
    <label>Additional Quantities (2)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Additional_Quantities_3__c.field-meta.xml
<CustomField>
    <fullName>Additional_Quantities_3__c</fullName>
    <description>If any Additional Quantities are mentioned</description>
    <inlineHelpText
  >If any Additional Quantities are mentioned - Please specify here</inlineHelpText>
    <label>Additional Quantities (3)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Artwork__c.field-meta.xml
<CustomField>
    <fullName>Artwork__c</fullName>
    <description>QR - Quoting for Artwork description</description>
    <label>Artwork</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Binding__c.field-meta.xml
<CustomField>
    <fullName>Binding__c</fullName>
    <description>QR - Quoting Binding</description>
    <label>Binding</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Calendar_Size__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Size__c</fullName>
    <label>Calendar Size</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quote Requests</relationshipLabel>
    <relationshipName>Quote_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>2500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Grid__c.field-meta.xml
<CustomField>
    <fullName>Grid__c</fullName>
    <description>QR PDF field</description>
    <label>Grid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Imprint_Colors__c.field-meta.xml
<CustomField>
    <fullName>Imprint_Colors__c</fullName>
    <inlineHelpText>Please List PMS or CMYK</inlineHelpText>
    <label>Number of Imprint Colors</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Imprint_Location__c.field-meta.xml
<CustomField>
    <fullName>Imprint_Location__c</fullName>
    <label>Imprint Location</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Imprint_Method__c.field-meta.xml
<CustomField>
    <fullName>Imprint_Method__c</fullName>
    <label>Imprint Method</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Misc_Comments__c.field-meta.xml
<CustomField>
    <fullName>Misc_Comments__c</fullName>
    <description>QR needed - Misc. Comments</description>
    <label>Misc Comments</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quote Requests</relationshipLabel>
    <relationshipName>Quote_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Printing__c.field-meta.xml
<CustomField>
    <fullName>Printing__c</fullName>
    <label>Printing</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Production_Lead_Time__c.field-meta.xml
<CustomField>
    <fullName>Production_Lead_Time__c</fullName>
    <description>QR needed - Production Lead Time</description>
    <label>Production Lead Time</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Production_Site__c.field-meta.xml
<CustomField>
    <fullName>Production_Site__c</fullName>
    <inlineHelpText>If not indicated, Domestic is the default.</inlineHelpText>
    <label>Production Site</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
                <default>true</default>
                <label>Domestic</label>
            </value>
            <value>
                <fullName>Overseas</fullName>
            </value>
            <value>
                <fullName>Domestic &amp; Overseas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Program_Manager__c.field-meta.xml
<CustomField>
    <fullName>Program_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Manually filled in by users</description>
    <inlineHelpText>Please select the correct Program Manager</inlineHelpText>
    <label>Program Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>Quote_Number__c</fullName>
    <displayFormat>Q-{0000}-{MMDDYY}</displayFormat>
    <label>Quote Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Quote_Request_Closed_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_Request_Closed_Date__c</fullName>
    <label>Quote Request Closed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Ships_From__c.field-meta.xml
<CustomField>
    <fullName>Ships_From__c</fullName>
    <description>QR - Quoting Ships From text field</description>
    <label>Ships From</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Style_Number_of_Sheets__c.field-meta.xml
<CustomField>
    <fullName>Style_Number_of_Sheets__c</fullName>
    <label>Style / Number of Sheets</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Valid_Through__c.field-meta.xml
<CustomField>
    <fullName>Valid_Through__c</fullName>
    <description>QR Needed - Gen Quote</description>
    <label>Valid Through</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/attachPDFToQuoteRequest.cls
/**
 * @description       : 
 * @author            : Sandeep Reddy
 * @group             : 
 * @last modified on  : 12-19-2022
 * @last modified by  : Sandeep Reddy
**/
public class attachPDFToQuoteRequest {
    private final Quote_Request__c QRequest; //Account object
    public string recordId;
    public Quote_Request__c QuoteRequestDetails{get;set;}
  //  public AccountTeamMember atm{get;set;}
    public Account acnt{get;set;}
    
    //constructor extension
    public attachPDFToQuoteRequest(ApexPages.StandardController standardPageController) {
        
        QRequest = (Quote_Request__c)standardPageController.getRecord(); //instantiate the Quote_Request__c object for the current record
        
    }
    
    //constructor
    public attachPDFToQuoteRequest() {
        
        // fetch the record id from the url then do soql and fetch out the quote detals on the basis of record id 
        string  recordId = apexpages.currentpage().getparameters().get('Recordid');
        QuoteRequestDetails = [SELECT Name,Imprint_Location__c,Imprint_Colors__c,Imprint_Method__c,Program_Manager__r.name,Program_Manager__r.Email,Program_Manager__r.Phone,Account__r.Primary_Team_Member2__r.name, Quote_Number__c, Account__c, Production_Site__c, Assigned_To__r.Name, Account__r.Primary_Team_Member2__c,
                               Account__r.Name, Account__r.AccountNumber, Account__r.Currency__c, Account__r.EBS_Num__c, Account__r.ShippingStreet,
                               Account__r.ShippingCity, Account__r.ShippingState, Account__r.ShippingPostalCode, Account__r.ShippingCountry,
                               Contact__r.Name, Contact__r.Email, Opportunity__r.Name, Valid_Through__c, Quote_Request_Closed_Date__c,
                               (SELECT Id,Imprint_Location__c,Number_of_Imprint_Colors__c,Imprint_Method__c, Name, Calendar_Size__c,Style_Number_of_Sheets__c, Binding__c,
                                Artwork__c,Price__c, Grid__c, Printing__c, Description__c,
                                Proofs__c, Production_Lead_Time__c, Quantity__c,Additional_Quantities__c,Additional_Quantities_2__c,Additional_Quantities_3__c,Additional_Qty_1_Price__c,Additional_Qty_2_Price__c,Additional_Qty_3_Price__c, Ships_From__c, 
                                Misc_Comments__c, Packing_approx__c, Sample_Lead_Time__c, Ocean_Transit__c,
                                Products__r.Name, Products__r.Product_ID__c
                                FROM Quote_Products__r)
                               FROM Quote_Request__c WHERE Id=:recordId];

        /*acnt = [SELECT Name, AccountNumber, Currency__c, ShippingStreet, ShippingCity, ShippingState, ShippingPostalCode, ShippingCountry 
                FROM Account WHERE Id =: QuoteRequestDetails.Account__c];
        ShippingStreet, ShippingCity, ShippingState, ShippingPostalCode, ShippingCountry
        
        system.debug('Account Address1 ---> '+acnt.ShippingCity);
        system.debug('Account Address2 ---> '+acnt.ShippingStreet);*/
        
      /*  if(!test.isRunningTest()){
            atm = [SELECT Id, AccountId, UserId, User.Name, User.Email, TeamMemberRole FROM AccountTeamMember Where 
                   AccountId =: QuoteRequestDetails.Account__c AND TeamMemberRole = 'Program Manager'];
        }*/
          
    }
    
    @AuraEnabled
    public static void attachPDF(string recordId,String Type) {
        
        set<string> documentidset = new set<string>();
        list<ContentDocumentLink> ContentDocumentLinkList =[select id,contentdocumentid from ContentDocumentLink where LinkedEntityId =:recordId];
        if(!ContentDocumentLinkList.isempty()){
             for(ContentDocumentLink CDL : ContentDocumentLinkList){
            documentidset.add(CDL.contentdocumentid);
        }
        }
       
        string Condition = '';
        //generate and attach the PDF document
        Blob pdfBlob; //create a blob for the PDF content
        if(Type =='Calendar'){
            Condition = 'Calendar%';
            PageReference pdfPage = Page.Calendar_Quote_PDF;
            System.debug('pdfPage : '+pdfPage);
             
            pdfPage.getParameters().put('Recordid',recordId);
            
            if (!Test.isRunningTest()) {
                pdfBlob = pdfPage.getContent(); //generate the pdf blob
            } else { 
                pdfBlob = Blob.valueOf('Some Text for a boring PDF file...');
            }
        }
        else{
            Condition ='HS_Quote%';
            PageReference pdfPage = Page.HS_Quote_PDF; 
            pdfPage.getParameters().put('Recordid',recordId);
            
            if (!Test.isRunningTest()) { 
                pdfBlob = pdfPage.getContent(); //generate the pdf blob
            } else { 
                pdfBlob = Blob.valueOf('Some Text for a boring PDF file...');
            }
            
        }
        //  Attachment attach = new Attachment(parentId = recordId, Name = DocName, body = pdfBlob); //create the attachment object
        //insert attach; //insert the attachment
        List<ContentVersion> contentVersionList = new List<ContentVersion> ();
        if(documentidset !=null){
                     contentVersionList = [SELECT Id, Title, ContentDocumentId 
                                                   FROM ContentVersion WHERE ContentDocumentId IN :documentidset and title like:Condition];
        }

        Integer Version =contentVersionList.size() + 1;
        String DocName = Type+'Quote_Version'+Version+'.pdf';
        
        ContentVersion contentVersion_1 = new ContentVersion(
            Title=DocName, 
            PathOnClient =DocName,
            VersionData = pdfBlob, 
            origin = 'H'
        );
        insert contentVersion_1;
        
        ContentVersion contentVersion_2 = [SELECT Id, Title, ContentDocumentId 
                                           FROM ContentVersion WHERE Id = :contentVersion_1.Id LIMIT 1];
        
        ContentDocumentLink contentlink = new ContentDocumentLink();
        contentlink.LinkedEntityId = recordId;
        contentlink.contentdocumentid = contentVersion_2.contentdocumentid;
        contentlink.ShareType = 'V';
        insert contentlink;
    }
    
}