force-app/main/default/objects/Quote_Request__c/Quote_Request__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Quote_Request_Compact_Layout</compactLayoutAssignment>
    <label>Quote Request</label>
    <nameField>
        <displayFormat>QR-{0000}</displayFormat>
        <label>Quote Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.AccountNumber</field>
            <operation>equals</operation>
            <valueField>Account.AccountNumber</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Requests</relationshipLabel>
    <relationshipName>Quote_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Additional_Files_or_Images__c.field-meta.xml
<CustomField>
    <fullName>Additional_Files_or_Images__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Additional Files or Images?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Calendar_Size__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Size__c</fullName>
    <label>Calendar Size</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Calendar_Year__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Year__c</fullName>
    <label>Calendar Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Competitor_Price__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Price__c</fullName>
    <inlineHelpText>For Price Match</inlineHelpText>
    <label>Competitor Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quote Requests</relationshipLabel>
    <relationshipName>Quote_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>2500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/In_Hands_Date_Event_Date__c.field-meta.xml
<CustomField>
    <fullName>In_Hands_Date_Event_Date__c</fullName>
    <label>In-Hands Date / Event Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quote Requests</relationshipLabel>
    <relationshipName>Quote_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Previous_Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>Previous_Quote_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Quote Number</label>
    <referenceTo>Quote_Request__c</referenceTo>
    <relationshipLabel>Child Quote Requests</relationshipLabel>
    <relationshipName>Quote_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Price_Point__c.field-meta.xml
<CustomField>
    <fullName>Price_Point__c</fullName>
    <label>Price Point</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <inlineHelpText
  >Stockline is any Catalog Product with no changes or alterations.
Modified Stockline is any Catalog Product that is altered.
Special Packaging is any non-standard packing request.
Custom is any item not within our Catalog assortment.
If multiple options apply, please select custom.</inlineHelpText>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stockline</fullName>
            </value>
            <value>
                <fullName>Modified Stockline</fullName>
            </value>
            <value>
                <fullName>Special Packaging</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Stockline Special Pack</fullName>
                <isActive>false</isActive>
                <label>Stockline Special Pack</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Production_Site__c.field-meta.xml
<CustomField>
    <fullName>Production_Site__c</fullName>
    <inlineHelpText>If not indicated, Domestic is the default.</inlineHelpText>
    <label>Production Site</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
                <default>true</default>
                <label>Domestic</label>
            </value>
            <value>
                <fullName>Overseas</fullName>
            </value>
            <value>
                <fullName>Domestic &amp; Overseas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Program_Manager__c.field-meta.xml
<CustomField>
    <fullName>Program_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Manually filled in by users</description>
    <inlineHelpText>Please select the correct Program Manager</inlineHelpText>
    <label>Program Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Quote_Amount__c.field-meta.xml
<CustomField>
    <fullName>Quote_Amount__c</fullName>
    <label>Quote Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Quote_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Quote_Request_Type__c</fullName>
    <label>Quote Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Universal Source</fullName>
            </value>
            <value>
                <fullName>Non_Calendar</fullName>
                <label>Non-Calendar</label>
            </value>
            <value>
                <fullName>Custom Calendar</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
                <isActive>false</isActive>
                <label>Custom</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Stationary</fullName>
                <isActive>false</isActive>
                <label>Stationary</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request in Draft</fullName>
                <default>true</default>
                <label>Request in Draft</label>
            </value>
            <value>
                <fullName>Request Submitted</fullName>
            </value>
            <value>
                <fullName>Request Received</fullName>
            </value>
            <value>
                <fullName>Request in Progress</fullName>
            </value>
            <value>
                <fullName>Request Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stage__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Art</fullName>
            </value>
            <value>
                <fullName>Pending Asia</fullName>
            </value>
            <value>
                <fullName>Pending CS/Sales</fullName>
            </value>
            <value>
                <fullName>Pending Customer</fullName>
            </value>
            <value>
                <fullName>Pending Internal Other</fullName>
                <label>Pending Internal/Other</label>
            </value>
            <value>
                <fullName>Pending Logistics</fullName>
            </value>
            <value>
                <fullName>Pending Manager Approval</fullName>
            </value>
            <value>
                <fullName>Pending Production</fullName>
            </value>
            <value>
                <fullName>Pending Purchasing</fullName>
            </value>
            <value>
                <fullName>Pending Quote Team</fullName>
            </value>
            <value>
                <fullName>Pending Vendor</fullName>
            </value>
            <value>
                <fullName>Waiting for Customer Response</fullName>
            </value>
            <value>
                <fullName>Closed - Sent to customer</fullName>
            </value>
            <value>
                <fullName>Customer/Sales Requested</fullName>
                <label>Cancelled – Customer/Sales Requested</label>
            </value>
            <value>
                <fullName>Cancelled – production cannot produce</fullName>
            </value>
            <value>
                <fullName
        >Cancelled - Pricing available on internal website</fullName>
                <label>Cancelled - Pricing available on internal website</label>
            </value>
            <value>
                <fullName>Cancelled - Not meeting MOQ</fullName>
            </value>
            <value>
                <fullName>Cancelled - In hands cannot be met</fullName>
            </value>
            <value>
                <fullName>Cancelled - Duplicate</fullName>
            </value>
            <value>
                <fullName>Cancelled - No Response</fullName>
            </value>
            <value>
                <fullName>Cancelled - Sent to Wrong Department</fullName>
            </value>
            <value>
                <fullName
        >Cancelled – not enough info submitted/invalid</fullName>
                <label>Cancelled – not enough info submitted/invalid</label>
            </value>
            <value>
                <fullName>New/Draft</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Cancelled - By Customer/Sales Rep</fullName>
                <isActive>false</isActive>
                <label>Cancelled - By Customer/Sales Rep</label>
            </value>
            <value>
                <fullName>Cancelled - Miscellaneous</fullName>
                <isActive>false</isActive>
                <label>Cancelled - Miscellaneous</label>
            </value>
            <value>
                <fullName>Cancelled - Production Cannot Produce</fullName>
                <isActive>false</isActive>
                <label>Cancelled - Production Cannot Produce</label>
            </value>
            <value>
                <fullName>Completed - Sent to customer</fullName>
                <isActive>false</isActive>
                <label>Completed - Sent to customer</label>
            </value>
            <value>
                <fullName>Completed -High priority</fullName>
                <isActive>false</isActive>
                <label>Completed -High priority</label>
            </value>
            <value>
                <fullName>Waiting for Asia info</fullName>
                <isActive>false</isActive>
                <label>Waiting for Asia info</label>
            </value>
            <value>
                <fullName>Waiting for Creative Services</fullName>
                <isActive>false</isActive>
                <label>Waiting for Creative Services</label>
            </value>
            <value>
                <fullName
        >Waiting for Customer Service or Sales Information</fullName>
                <isActive>false</isActive>
                <label>Waiting for Customer Service or Sales Information</label>
            </value>
            <value>
                <fullName>Waiting for Internal department</fullName>
                <isActive>false</isActive>
                <label>Waiting for Internal department</label>
            </value>
            <value>
                <fullName>Waiting for Logistics</fullName>
                <isActive>false</isActive>
                <label>Waiting for Logistics</label>
            </value>
            <value>
                <fullName>Waiting for Production info</fullName>
                <isActive>false</isActive>
                <label>Waiting for Production info</label>
            </value>
            <value>
                <fullName>Waiting for Vendor info</fullName>
                <isActive>false</isActive>
                <label>Waiting for Vendor info</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CloneQuoteRequestController.cls
public class CloneQuoteRequestController {
    
    @AuraEnabled
    public static String createQuoteRequest(Map<String, Object> quoteRequestProxy, Id recordId, String recordTypeId)
    {
        
        Id quoteRequestCustomRecordTypeId = Schema.SObjectType.Quote_Request__c.getRecordTypeInfosByName().get('Custom Calendar').getRecordTypeId();
        Id quoteRequestNonRecordTypeId = Schema.SObjectType.Quote_Request__c.getRecordTypeInfosByName().get('Non-Calendar').getRecordTypeId();
        Id quoteProductCustomRecordTypeId = Schema.SObjectType.Quote_Product__c.getRecordTypeInfosByName().get('Custom Calendar').getRecordTypeId();
        Id quoteProductNonRecordTypeId = Schema.SObjectType.Quote_Product__c.getRecordTypeInfosByName().get('Non-Calendar').getRecordTypeId();
        
        System.debug('Custom Rec Id ===> '+quoteRequestCustomRecordTypeId);
        System.debug('Non Rec Id ===> '+quoteRequestNonRecordTypeId);
        //System.debug('Assigned to ===> '+assignedTo);
        System.debug('<=== Before QR Insert ===>');

        String assignedTo =  (String)QuoteRequestProxy.get('Assigned_To__c');
        String opportunity =  (String)QuoteRequestProxy.get('Opportunity__c');
        
        system.debug('opportunity@@@@'+opportunity);
        Quote_Request__c qr = new Quote_Request__c();
     //   qr.Previous_Quote_Number__c = (String)QuoteRequestProxy.get('Previous_Quote_Number__c');
        qr.Previous_Quote_Number__c = recordId;
        qr.Account__c = (String)QuoteRequestProxy.get('Account__c');
        if (opportunity !=null && opportunity.length() > 15)
        {
            qr.Opportunity__c = opportunity;
        }
        qr.Project_Name__c = (String)QuoteRequestProxy.get('Project_Name__c');
        qr.Contact__c = (String)QuoteRequestProxy.get('Contact__c');
        qr.Additional_Files_or_Images__c = (Boolean)QuoteRequestProxy.get('Additional_Files_or_Images__c');
        qr.Production_Site__c = (String)QuoteRequestProxy.get('Production_Site__c');
        qr.Product_Type__c = (String)QuoteRequestProxy.get('Product_Type__c');
        if(assignedTo != null && assignedTo.length() > 3)
        {
            qr.Assigned_To__c = assignedTo;
        }
        qr.Stage__c = (String)QuoteRequestProxy.get('Stage__c');
        qr.Status__c = (String)QuoteRequestProxy.get('Status__c');
        qr.Quote_Amount__c = (Decimal)QuoteRequestProxy.get('Quote_Amount__c');
        qr.Price_Point__c = (Decimal)QuoteRequestProxy.get('Price_Point__c');
        qr.Competitor_Price__c = (Decimal)QuoteRequestProxy.get('Competitor_Price__c');
        qr.Currency__c = (String)QuoteRequestProxy.get('Currency__c');
        system.debug('Before Record Type Line');
        if(recordTypeId == quoteRequestCustomRecordTypeId)
        {
            qr.Program_Manager__c = (String)QuoteRequestProxy.get('Program_Manager__c');
            qr.Quote_Request_Type__c = 'Custom Calendar';
        }
        qr.RecordTypeId = recordTypeId;
        //qr.In_Hands_Date_Event_Date__c = (Date)QuoteRequestProxy.get('In_Hands_Date_Event_Date__c');
        insert qr;
        
        
        system.debug('After Quote Request Insertion');
        
        List<Quote_Product__c> quoteProducts = [SELECT Id, Name, Quote_Request__c, RecordTypeId, Products__c, Calendar_Year__c, Description__c,
                                                Calendar_Size__c, Style_Number_of_Sheets__c, Binding__c, Artwork__c, Grid__c, Printing__c, 
                                                Same_Ad_on_All__c, Quantity__c, Additional_Quantities__c, Additional_Quantities_2__c, 
                                                Additional_Quantities_3__c, Additional_Information__c, Price_Point__c, Imprint_Location__c, 
                                                Imprint_Method__c, Number_of_Imprint_Colors__c, Addt_l_Comments__c
                                                FROM Quote_Product__c
                                                WHERE Quote_Request__c =: recordId];  
        
        System.debug('Quote Products Size'+quoteProducts.size());
        
        List<Quote_Request__c> QuoteRequestClone = [SELECT Id, Name, RecordTypeId, Account__c, Opportunity__c, Contact_Email__c FROM Quote_Request__c WHERE Id =: qr.Id];
        
        System.debug('Quote Request Clone ==> '+QuoteRequestClone);
        
        List<Quote_Product__c> clonedQuoteProducts = new List<Quote_Product__c>();
        
        if(quoteProducts.size()>0)
        {
            
            for (Quote_Product__c originalQuoteProduct : quoteProducts) 
            {
                
                Quote_Product__c clonedQuoteProduct = new Quote_Product__c();
                clonedQuoteProduct.Quote_Request__c 			= QuoteRequestClone[0].Id;
                clonedQuoteProduct.Products__c 					= originalQuoteProduct.Products__c;
                clonedQuoteProduct.Quantity__c 					= originalQuoteProduct.Quantity__c;
                clonedQuoteProduct.Additional_Quantities__c 	= originalQuoteProduct.Additional_Quantities__c;
                clonedQuoteProduct.Additional_Quantities_2__c	= originalQuoteProduct.Additional_Quantities_2__c;
                clonedQuoteProduct.Additional_Quantities_3__c	= originalQuoteProduct.Additional_Quantities_3__c;
                clonedQuoteProduct.Additional_Information__c	= originalQuoteProduct.Additional_Information__c;
                clonedQuoteProduct.Addt_l_Comments__c 			= originalQuoteProduct.Addt_l_Comments__c;
                
                if(recordTypeId == quoteRequestCustomRecordTypeId)
                {
                    
                    if(originalQuoteProduct.RecordTypeId == quoteProductCustomRecordTypeId)
                    {
                        
                        clonedQuoteProduct.Calendar_Year__c 			= originalQuoteProduct.Calendar_Year__c;
                        clonedQuoteProduct.Description__c 				= originalQuoteProduct.Description__c;
                        clonedQuoteProduct.Calendar_Size__c 			= originalQuoteProduct.Calendar_Size__c;
                        clonedQuoteProduct.Style_Number_of_Sheets__c 	= originalQuoteProduct.Style_Number_of_Sheets__c;
                        clonedQuoteProduct.Binding__c 					= originalQuoteProduct.Binding__c;
                        clonedQuoteProduct.Artwork__c 					= originalQuoteProduct.Artwork__c;
                        clonedQuoteProduct.Grid__c 						= originalQuoteProduct.Grid__c;
                        clonedQuoteProduct.Printing__c 					= originalQuoteProduct.Printing__c;
                        clonedQuoteProduct.Same_Ad_on_All__c 			= originalQuoteProduct.Same_Ad_on_All__c;
                        clonedQuoteProduct.RecordTypeId                 = originalQuoteProduct.RecordTypeId;
                        
                    }
                }
                else if(recordTypeId == quoteRequestNonRecordTypeId)
                {
                    
                    if(originalQuoteProduct.RecordTypeId == quoteProductNonRecordTypeId)
                    {
                        
                        clonedQuoteProduct.Price_Point__c 				= originalQuoteProduct.Price_Point__c;
                        clonedQuoteProduct.Imprint_Location__c 			= originalQuoteProduct.Imprint_Location__c;
                        clonedQuoteProduct.Imprint_Method__c 			= originalQuoteProduct.Imprint_Method__c;
                        clonedQuoteProduct.Number_of_Imprint_Colors__c 	= originalQuoteProduct.Number_of_Imprint_Colors__c;
                        clonedQuoteProduct.RecordTypeId                 = originalQuoteProduct.RecordTypeId;
                    }
                }
                
                clonedQuoteProducts.add(clonedQuoteProduct);
            }
            
        }
        
        System.debug('Cloned Quote Products Size ===> '+clonedQuoteProducts.size());
        
        if(clonedQuoteProducts.size()>0)
        {
            insert clonedQuoteProducts;
        }
        
        return QuoteRequestClone[0].Name;
        
    }
    
}