force-app/main/default/objects/Quote_Request__c/Quote_Request__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Quote_Request_Compact_Layout</compactLayoutAssignment>
    <label>Quote Request</label>
    <nameField>
        <displayFormat>QR-{0000}</displayFormat>
        <label>Quote Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quote Requests</relationshipLabel>
    <relationshipName>Quote_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RelatedQuoteRequestsControllerTest.cls
@isTest
public class RelatedQuoteRequestsControllerTest {

    @isTest
    public static void testGetRelatedQuoteRequests() {
        Opportunity opp = new Opportunity(Name = 'Test Opportunity', StageName = 'Prospecting', CloseDate = Date.today());
        insert opp;
        Quote_Request__c quoteRequest = new Quote_Request__c(Opportunity__c = opp.Id);
        insert quoteRequest;
        Quote_Product__c quoteProduct = new Quote_Product__c(
            Quote_Request__c = quoteRequest.Id
        );
        insert quoteProduct;
        List<Quote_Product__c> result = RelatedQuoteRequestsController.getRelatedQuoteRequests(opp.Id);
        System.assertEquals(1, result.size());
        System.assertEquals(quoteProduct.Id, result[0].Id);
    }
}