force-app/main/default/objects/Quote_Request__c/Quote_Request__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Quote_Request_Compact_Layout</compactLayoutAssignment>
    <label>Quote Request</label>
    <nameField>
        <displayFormat>QR-{0000}</displayFormat>
        <label>Quote Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quote Requests</relationshipLabel>
    <relationshipName>Quote_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Request__c/fields/Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>Quote_Number__c</fullName>
    <displayFormat>Q-{0000}-{MMDDYY}</displayFormat>
    <label>Quote Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/RelatedQuoteRequestsController.cls
public with sharing class RelatedQuoteRequestsController {
    @AuraEnabled(cacheable=true)
    public static List<Quote_Product__c> getRelatedQuoteRequests(String opportunityId) {
        system.debug('oppid@@@@@'+ opportunityId);
        List<Quote_Request__c>QuoteRequestList = new list<Quote_Request__c>();
        QuoteRequestList =[SELECT Id FROM Quote_Request__c WHERE Opportunity__c = :opportunityId ];
        List<Quote_Product__c>Quoteproducts =[SELECT Id, Name,Quote_Number__c,Quote_Request__c,	Quantity__c,Products__r.Name FROM Quote_Product__c where Quote_Request__c IN:QuoteRequestList ];
    return Quoteproducts;
    }
    
}